[package]
name = "dom5status"
version = "0.1.0"
authors = ["David McGillicuddy <contact@djmcgill.co.uk>"]

[dependencies]
byteorder = "*"
failure = "0.1.1"
flate2 = "1.0"
hex-slice = "*"
lazy_static = "*"
log = "0.4.*"
r2d2 = "0.8.2"
r2d2_sqlite = "0.5.0"
rusqlite = {version = "0.13.*", features = ["bundled", "trace"]}
serenity = "0.5.1"
simplelog = "^0.4.4"
typemap = "0.3"
url = "1.6.*"
either = "1.4"
itertools = "0.7.*"
enum-primitive-derive = "^0.1"
num-traits = "^0.1"
cached = { version = "0.5.0", git = "https://github.com/djmcgill/cached" }
migrant_lib = { version = "0.19.2", features = ["d-sqlite"]}
tcmalloc = {version = "0.1.3", git = "https://github.com/jmcomets/tcmalloc-rs.git" }
