version: 2
jobs:
  build:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      # - restore_cache:
      #     keys:
      #       - cargo-cache-{{ checksum "Cargo.toml" }}
      #       - cargo-cache-
      # - run: cargo build
      # - run: cargo test
      # EU_GCR_API_KEY_JSON
      - setup_remote_docker
      - run: echo $EU_GCR_API_KEY_JSON | docker login -u _json_key --password-stdin https://eu.gcr.io
      # TODO: coverage https://abronan.com/building-a-rust-project-on-circleci/
      - run: docker build -t eu.gcr.io/dom-5-status/dom-5-status .

      # - save_cache:
      #     key: cargo-cache-{{ checksum "Cargo.toml" }}
      #     paths:
      #       - "~/.cargo"
      #       - "./target"
      #       - "/usr/local/cargo"

  deploy:
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker
      - run: echo $EU_GCR_API_KEY_JSON | docker login -u _json_key --password-stdin https://eu.gcr.io
      - run: docker build -t eu.gcr.io/dom-5-status/dom-5-status .
      - run: docker push eu.gcr.io/dom-5-status/dom-5-status 
      
      - run: echo $EU_GCR_API_KEY_JSON | docker login -u _json_key --password-stdin https://eu.gcr.io
      - add_ssh_keys
      - run:
          name: SSH to server and deploy
          command: |
            ssh -o "StrictHostKeyChecking=no" \
                   "$SSH_ADDRESS" \
                   "cat json.key | docker login -u _json_key --password-stdin https://eu.gcr.io; \
                    docker pull eu.gcr.io/dom-5-status/dom-5-status; \
                    RUNNING_CONTAINERS=docker ps -q; \
                    if [ ! -z $RUNNING_CONTAINERS ]; then docker stop $RUNNING_CONTAINERS; fi; \
                    docker run -it -d \
                      --restart unless-stopped \
                      --volume /app/resources:/usr/src/myapp/resources  \
                      eu.gcr.io/dom-5-status/dom-5-status"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy_approval:
          type: approval
          requires:
           - build
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
            - deploy_approval
          filters:
            branches:
              only: master
